package com.georgkivivali.jalgrattaliiklustestidapi.bicycletest;

/**
 * Enum to store all the possible categories which a test can have.
 */
public enum TestCategories {
    TEEANDMISE_KOHUSTUS,
    SÕIDUKI_ASUKOHT_SÕITMISEL,
    VASAK_JA_TAGASIPÖÖRE,
    ÜMBERPÕIGE,
    SÕITMINE_RISTMIKEL,
    SÕIDUTEE_ÜLETAMINE_ÜLEKÄIGUKOHA_VÕI_ÜLEKÄIGURAJA_KAUDU,
    JUHI_KOHUSTUSED_JALAKÄIJATE_OHUTUSE_TAGAMISEL,
    SÕITMINE_JALGRATTATEEL_VÕI_JALGRATTA_JA_JALGTEEL,
    SÕITMINE_PIMEDA_AJAL_VÕI_HALVA_NÄHTAVUSE_TINGIMUSTES,
    JALGRATTURI_JA_PISIMOPEEDIJUHI_OHUTUS_JA_KÄITUMINE_LIIKLUSES
}
